### ISSUE TITLE
[Bug] Disappearing, not showed Tabs

### ISSUE THREAD

**Issue by moszeed** [traxium/tabtree#2]
Sometimes if i create Tab, i can use it normal, 
but if i click on a other Tab the new created Tab is not Displayed in "tabstree".
To get the new created Tab, i have to repeatedly open new Tabs until the "new created" Tabs
appears!

**Comment by traxium** [comment]
What way to create a new tab do you use? Ctrl+t, double click or another way? Are you sure you don't use "Tab Groups (Panorama)" in Firefox and you have only one "tab group"? Are there any errors in the Browser Console (Ctrl+Shift+j) in the file "bootstrap.js"?
Thank you for taking the time to report this bug.

**Comment by moszeed** [comment]
Both ways, Ctrl+T and double click.
I`m using the 42.0a1 (Firefox Nightly) ...
Browser Console is silent, no errors, no bootstrap.js ...

**Comment by strigona** [comment]
In my experience, the last tab on the tree is the one that's not being displayed. I can Ctrl + Tab to access it, but the tab itself is simply not visible on the tree.

Firefox 41.0b1

**Comment by strigona-worksight** [comment]
Opening the addon settings and toggling the Left/Right option corrects this issue.

**Comment by strigona-worksight** [comment]
I can only imagine that it's related, but I've also experienced the opposite, where there's an extra item on the tab list as can be seen here: http://i.imgur.com/BOOmpdc.png

**Comment by traxium** [comment]
Fixed in version 1.1.2. Bug was introduced in Firefox 41.0 and was caused by changes in Firefox internal Session Store API. The bug showed itself only after Firefox restart/shutdown and was related to number of pinned tabs.

**Comment by strigona-worksight** [comment]
1.1.2 or 1.2.2? I just got 1.1.2 and it's not fixed. Additionally, I don't see any source for 1.1.2.

I have been able to consistently reproduce the issue using the [CommaFeed addon](https://addons.mozilla.org/en-US/firefox/addon/commafeed/?src=api):

When the CommaFeed webpage is NOT open, click on the toolbar icon which opens the CommaFeed webpage in a new tab. For me, this new tab is rarely listed on the tree.

Additionally, closing the CommaFeed tab using Ctrl+W will cause the tab at the bottom of the list to be removed from the list.

You can repeat the above steps to cause the tree to no display many tabs. As I gather, the addon maintains it's own list of open tabs and the addon is not capturing all types of tab creating events.

Finally, if you use Ctrl+Shift+T to restore a close tab, this causes the addon to re-sync itself with the browser and displays all tabs properly.

**Comment by traxium** [comment]
It's version 1.1.2. I'll push it here today or tomorrow. Maybe there is another bug that you are describing. I'll look at it. Thank you for a way to reproduce that bug. It'll help greatly.

**Comment by strigona-worksight** [comment]
OK, no problem.

The CommaFeed example doesn't happen 100% of the time, but definitely most of the time.

**Comment by traxium** [comment]
I inadvertently updated my own add-on recently and It replaced the project folder (with .git repository inside it) with .xpi file from AMO. That was nasty.

**Comment by strigona** [comment]
I just got 1.1.4 and it looks good to me. I'll test some more tomorrow.

**Comment by moszeed** [comment]
Updated yesterday. Since then, no disappearing Tabs! Great! Thx!
