### ISSUE TITLE
One tab is missing

### ISSUE THREAD

**Issue by Bu11etmagnet** [traxium/tabtree#27]
One tab is missing from the list. There were three pinned tabs (Gmail, Jira, Hudson), a Google search, the Add-on Manager, and tabtree's GitHub page. However, the GitHub page is not visible in the tree and can't be selected with the mouse.
![tabtree-missing-screenshot](https://cloud.githubusercontent.com/assets/7579651/10159793/d902faf0-669a-11e5-888b-54c223af2b03.png)

**Comment by traxium** [comment]
I presume you don't use Tab Groups?
If you know a way to reproduce this bug, please, let me know. Unless I know how to reproduce the bug it's very hard to fix it. Maybe one of your extensions could cause this bug? Or you did something special before?
By the way, changing the tab tree position from left to right (or vice versa) or disabling/enabling this add-on or Firefox restart should fix it.

**Comment by Bu11etmagnet** [comment]
It seems it's always the last created tab that's missing.
Changing the tab tree position does make the problem go away.

I don't use Tab Groups, however I have Tree Style Tab installed but disabled:

Extensions
Name |   Version  |       Enabled    |     ID
-----|------------|------------------|-------
Classic Theme Restorer | 1.4.0   | true |    ClassicThemeRestorer@ArisT2Noia4dev
DOM Inspector  | 2.0.16  | true |    inspector@mozilla.org
Download Status Bar  |   12.3.0.1-signed | true |    {6c28e999-e900-4635-a39d-b1ec90ba0c0f}
Edit Bookmark Plus   |   2.3.2   | true |    edit-bookmark-plus@kashiif-gmail.com
Html Validator  | 0.9.5.8 | true |    {3b56bcc7-54e5-44a2-9b44-66c3ef58c13e}
Hungarian dictionary  |  1.6.1.1 | true |    hu@dictionaries.addons.mozilla.org
Live HTTP headers     |  0.17.1-signed   | true |    {8f8fe09b-0bd3-4470-bc1b-8cad42b8203a}
MinimizeToTray revived (MinTrayR)   |    1.1.2.1-signed  | true |    mintrayr@tn123.ath.cx
NoScript    |    2.6.9.37        | true |    {73a6fe31-595d-460b-a920-fcc0f8843232}
RequestPolicy |  1.0.0b3 | true |    requestpolicy@requestpolicy.com
RSS Icon in url bar  |   1.5.2   | true |    rssicon.vaka@gmail.com
Squared Australis Tabs | 1.5     | true |    squaredaustralistabs@haven667
Tab Tree      |  1.3.5   | true |    TabsTree@traxium
uBlock Origin  | 1.1.1   | true |    uBlock0@raymondhill.net
Universal Edit Button Auto-Discovery |   1.3.1-signed    | true |    button@wikihow.com
Adblock Edge  |  2.1.9.1-signed  | false |   {fe272bd1-5f76-4ea4-8501-a05d35d823fc}
Firebug | 2.0.12  | false |   firebug@software.joehewitt.com
Ghostery  |      5.4.8.1 | false |   firefox@ghostery.com
S3 Firefox Organizer(S3Fox)   |  0.6     | false |   {7CEA821D-3DAB-4238-B424-BF7324531750}
Status-4-Evar  | 2015.02.06.23.1-signed  | false |   status4evar@caligonstudios.com
Tree Style Tab | 0.15.2015030601 | false |   treestyletab@piro.sakura.ne.jp
Ubuntu Modifications | 3.2  |    false |  ubufox@ubuntu.com

**Comment by Bu11etmagnet** [comment]
A data point: this happened today when NoScript was updated and its "What's new" page was displayed (this page did not appear on the list). After restarting Firefox, the "What's new" page was not displayed and all tabs were listed as expected.

So maybe NoScript displays its "What's new" page in a way that TabTree does not know about it?

**Comment by traxium** [comment]
It was indeed the case. You helped me a lot. I'm very grateful. Of course there can be other bugs causing a missing tab but this bug with the "What's new" page (actually it was `gBrowser.addTab()` without arguments) is fixed.

**Comment by Bu11etmagnet** [comment]
Alas, it's still happening with TabTree 1.3.6 :(

**Comment by traxium** [comment]
This bug is fixed in 1.3.7.

**Comment by traxium** [comment]
1.3.7 was approved on AMO today.

**Comment by jtojnar** [comment]
The issue is still occurring with 1.3.7 when Firefox is terminated and the session is restored using the built-in Session Manager.

I have four pinned tabs and last four tabs aren’t visible. When I open new tab at the end, the first of the hidden tabs will appear. When I close the opened tab, it will disappear again.  If I unpin or re-pin the pinned tabs, the hidden tabs will remain hidden.

When I exit Firefox gracefully and re-start it, the tabs will be visible again. (I have “Show my windows and tabs from last time” option selected in Firefox options.)

**Comment by skrzyp** [comment]
Same here, I can confirm that on Linux and Windows 10 separately.
My addons are: uBlock Origin, Auto Unload Tab, Tab Tree, Classic Theme Restorer.

**Comment by traxium** [comment]
I fixed missing tabs when they are restored by the build-in Session Manger. The fix will be available in version 1.3.9.
But there is still small possibility that I haven't covered all cases when one (or more) tabs were missed. If you encounter such a case please let me know and I'll try to fix it.

**Comment by traxium** [comment]
Please, let me know if this bug still happens sometimes.

**Comment by skrzyp** [comment]
I was switched to Chromium for some reasons for a while, but I'm going back to Fx so I'll let you know about this soon.

**Comment by skrzyp** [comment]
Now tabs are not missing, but they can't be inherit - list is completely flatten.
I'm still using "Auto Unload Tab" addon.

**Comment by traxium** [comment]
As it seems the tabs aren't missing anymore. I couldn't reproduce the bug with "Auto Upload Tab" with the latest Tab Tree version. Please open a new issue or refer #108 (it looks similar) if this bag still remains. So I'll close the issue.
