### ISSUE TITLE
[Bug]Horizontal scrollbar

### ISSUE THREAD

**Issue by kshpytsya** [traxium/tabtree#38]
After activating tabtree in Firefox 41.0.2 a horizontal scrollbar appears on all pages.

**Comment by strigona-worksight** [comment]
I haven't noticed this in 42b9.

**Comment by kshpytsya** [comment]
Is "42b9" a commit or a Firefox version? AFAIK 41.0.2 is the current Firefox version so I would expect the tabtree work with it.

**Comment by strigona-worksight** [comment]
42b9 = 42.0 beta 9. 41.0.2 is a security patch/release and didn't have any other changes over 41.0.1. Therefore, if it was working under 41.0.1, it should be working under 41.0.2.

If you only just installed TabTree, then the issue could lie elsewhere, such as an incompatibility with another addon. If you're up for trying a few things, you could disable all other addons and see if the issue persists.

**Comment by kshpytsya** [comment]
I have disabled all extensions but TabTree and have restarted the browser. The problem persists. Can this be related to a relatively small (1024x600) screen size of the netbook I test this on? I have just found out that scrollbar appears without TabTree but with Firefox's Bookmarks Sidebar as well.

**Comment by strigona-worksight** [comment]
That is quite likely the cause. A lot of websites set a "minimum display width", if your screen is narrower than the min-width, the browser will add a scrollbar. If you click the "New Tab" button (+ symbol at the bottom of the tab tree, that page should not have a scrollbar.

**Comment by strigona-worksight** [comment]
FYI, there is an option to make the tree "auto-hide" when your mouse isn't hovering over the tab free. This should help give you back some screen real-estate.
